test:
  :address: smtp.gmail.com
  :port: 587
  :domain: www.gmail.com
  :user_name: pricecatcher1@gmail.com
  :password: forever924
  :authentication: plain
  :enable_starttls_auto: true
development:
  :address: smtp.gmail.com
  :port: 587
  :domain: www.gmail.com
  :user_name: pricecatcher1@gmail.com
  :password: forever924
  :authentication: plain
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :domain: www.gmail.com
  :user_name: pricecatcher1@gmail.com
  :password: forever924
  :authentication: plain
  :enable_starttls_auto: true

