development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: <%= ENV['CATCHER_USERNAME'] %>
  :password: %= ENV['CATCHER_PASSWORD'] %>
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: <%= ENV['CATCHER_USERNAME'] %>
  :password: %= ENV['CATCHER_PASSWORD'] %>
  :enable_starttls_auto: true